#!/bin/sh
set -eu

OUT="/etc/kismet/kismet_site.conf"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Autogenerated by K.A.R.I Kismet source autoconfig"
  echo "# Prefer wlan2 for passive Wi-Fi capture when present."
  echo "# Keep wlan0 untouched."
  echo

  if hciconfig hci0 >/dev/null 2>&1 || bluetoothctl list 2>/dev/null | grep -qi 'Controller '; then
    echo "source=hci0:type=linuxbluetooth"
  else
    echo "# hci0 not present; bluetooth source not configured"
  fi

  if ip link show wlan2 >/dev/null 2>&1; then
    echo "source=wlan2:type=linuxwifi"
  else
    echo "# wlan2 not present; no automatic Wi-Fi source configured"
    echo "# Add wlan1 manually from Kismet if needed"
  fi
} >"$TMP"

install -m 0644 "$TMP" "$OUT"
